[package]
name = "pgokf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["pg18"]
pg15 = ["pgrx/pg15"]
pg16 = ["pgrx/pg16"]
pg17 = ["pgrx/pg17"]
pg18 = ["pgrx/pg18"]
pg19 = ["pgrx/pg19"]
pg_test = []

[dependencies]
okf-parser = { version = "=0.1.0", path = "../okf-parser" }
okf-sync = { version = "=0.1.0", path = "../okf-sync" }
pgrx.workspace = true

[lints]
workspace = true
